### ISSUE TITLE
Search and Replace is only done on post_content

### ISSUE THREAD

**Issue by rbaugh** [short-pixel-optimizer/enable-media-replace#27]
Is there a reason why the search and replace is only being done on the post_content and not also on the meta_value? Using custom fields, the data is typically stored in the postmeta table and doesn't get updated. 

There was another version of this plugin that isn't being updated anymore and seems to have had this functionality in it:
https://github.com/mansj/enable-media-replace/blob/master/upload.php#L307

**Comment by rbaugh** [comment]
@short-pixel-optimizer Just checking in to see if you would be adding in the post_meta to the search and replace so that custom fields can also benefit from the search and replace for a new file. Otherwise we still end up with orphaned links on custom fields.

This has caused us and out client many  hours of headaches wondering why things were not updating with the new urls.

**Comment by short-pixel-optimizer** [comment]
@rbaugh thanks for pointing this issue out. As far as I can see the feature was removed previously to our takeover of the plugin. I could guess it was because of performance issues related to the select on the whole postmeta table, using a like.
Anyway, will definitely check how we can fix this (without impacting the performance) and will let you know.

**Comment by rbaugh** [comment]
Thanks. We have ACF fields for sites and the links for documents reside in them so they don't get updated and cause headaches.

**Comment by ethanclevenger91** [comment]
WP Offload Media adds a shortcode that is designed to mitigate this to some extent. It allows you to do something like:

`[amazon_s3 id="1629"]`

Which will turn into the URL for that attachment. Someone in this situation might consider recreating that shortcode for this same use case, creating a reference to the attachment instead of directly to the URL. Especially for document downloads where you're not fiddling with `<img src=...` anyway.
